<a href="https://colab.research.google.com/github/koongmai/Optimal-Algorithms/blob/main/CH02_%EC%8B%A4%EC%8A%B5_numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CH02 : 머신러닝을 위한 넘파이 라이브러리

### 1. 넘파이 라이브러리 불러오기

- Numpy 라이브러리는 머신러닝 관련 코드에서 많이 사용 되는(배열에 대한 다양한 수학 연산이 가능) 라이브러리이다.
- 아래 사이트는 Numpy 공식 도큐먼트 사이트로 Numpy에 대해서 더 알고 싶다면 해당 사이트를 방문하여 확인할 수 있다.

    [Numpy 공식 도큐먼트 사이트](https://numpy.org/doc/stable/user/absolute_beginners.html)


In [ ]:
# 넘파이 라이브러리를 np로 재정의하여 불러온다.
import numpy as np

- "print_obj"는 출력하려는 객체(object) "이름"과 객체가 실제 저장하는 내용(값)을 출력하는 역할을 한다.
    - cf. escape 이스케이프 코드 : \n - 문자열 안에서 줄을 바꿀 때 사용
    - cf. 포맷팅(Formatting) : 문자열안에 특정부분을 특정 변수의 위치로 정해줌으로써 해당 변수의 값에 따라 문자열 자체가 변경 될 수 있게 하는 기능

In [ ]:
# 객체와 객체의 이름을 입력하면 출력해주는 함수를 정의한다.
def print_obj(obj, name): #함수를 정의하겟다., 이 함수를 호출하면 그 함수의 내용이 실행됨.
    print("%s:\n%s\n" % (name, obj))

### 2. 스칼라(Scalars), 벡터(Vectors), 행렬(Matrices)

In [ ]:
# 임의의 배열을 스칼라, 벡터, 행렬 형태로 정의한다.
array0 = np.array(1.) # 0차원 배열, 스칼라
array1 = np.array([1., 2., 3.]) # 1차원 배열, 벡터
array2 = np.array([[1., 2., 3.], [4., 5., 6.]]) # 2차원 배열, 행렬

# 앞서 정의한 print_obj 함수를 이용해 출력한다.
print_obj(array0, "스칼라")
print_obj(array1, "벡터")
print_obj(array2, "행렬")

스칼라:
1.0

벡터:
[1. 2. 3.]

행렬:
[[1. 2. 3.]
 [4. 5. 6.]]



In [ ]:
# 정의한 스칼라, 벡터, 행렬의 차원을 출력한다.
print_obj(array0.ndim, "스칼라의 차원") # ndim → 차원의 크기 반환
print_obj(array1.ndim, "벡터의 차원")
print_obj(array2.ndim, "행렬의 차원")

스칼라의 차원:
0

벡터의 차원:
1

행렬의 차원:
2



In [ ]:
# 정의한 스칼라, 벡터, 행렬의 shape를 출력한다.
print_obj(array0.shape, "array0의 shape")
print_obj(array1.shape, "array1의 shape")
print_obj(array2.shape, "array2의 shape")
array3 = np.array([[1, 2, 3]])
print_obj(array3.shape, "array3의 shape")

array0의 shape:
()

array1의 shape:
(3,)

array2의 shape:
(2, 3)

array3의 shape:
(1, 3)



### 3. 텐서(Tensors)

In [ ]:
# 3차원 이상 배열로 구성된 텐서의 차원과 shape를 출력한다.
tensor1 = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
tensor2 = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
                    [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])


print_obj(tensor1, "tensor1")
print_obj(tensor1.ndim, "tensor1.ndim")
print_obj(tensor1.shape, "tensor1.shape")

print_obj(tensor2, "tensor2")
print_obj(tensor2.ndim, "tensor2.ndim")
print_obj(tensor2.shape, "tensor2.shape")

tensor1:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

tensor1.ndim:
3

tensor1.shape:
(2, 2, 3)

tensor2:
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

tensor2.ndim:
4

tensor2.shape:
(2, 2, 2, 3)



### 4. 넘파이 배열(Numpy arrays)

In [ ]:
# 원소가 1이고 크기가 10인 벡터를 넘파이 배열로 생성한다.
ones = np.ones(10)
print_obj(ones, "np.ones(10)")

np.ones(10):
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]



In [ ]:
# 원소가 0이고 크기가 235인 행렬을 넘파이 배열로 생성한다.
zeros = np.zeros((2, 5))
print_obj(zeros, "np.zeros((2, 5))")

np.zeros((2, 5)):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]



In [ ]:
# 파라미터에 배열의 크기와 값을 입력한다.
# 입력된 크기만큼의 배열을 만들고 입력한 값으로 배열을 채운다.
full = np.full((2, 5), 5)
print_obj(full, "np.full((2, 5), 5)")

full2 = np.full((1, 1, 1), -1)
print_obj(full2, "np.full((1, 1, 1), -1)")

np.full((2, 5), 5):
[[5 5 5 5 5]
 [5 5 5 5 5]]

np.full((1, 1, 1), -1):
[[[-1]]]



In [ ]:
random = np.random.random((2, 3, 4))
print_obj(random, "np.random.random((2, 3, 4))")

np.random.random((2, 3, 4)):
[[[0.69881615 0.44935173 0.09353458 0.05556524]
  [0.93799628 0.10206528 0.16754857 0.71706663]
  [0.92662971 0.37599751 0.65880275 0.25506203]]

 [[0.29377974 0.06485298 0.71047958 0.85469467]
  [0.2913893  0.73172962 0.54950003 0.97163931]
  [0.19022277 0.14998322 0.13682572 0.64788167]]]



In [ ]:
arange = np.arange(10)
print_obj(arange, "np.arange(10)")

np.arange(10):
[0 1 2 3 4 5 6 7 8 9]



In [ ]:
astype = np.arange(10).astype(float)
print_obj(astype, "np.arange(10).astype(float)")

np.arange(10).astype(float):
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]



In [ ]:
reshape = np.arange(10).reshape((5,2))
print_obj(reshape, "np.arange(10).reshape((5,2)")

np.arange(10).reshape((5,2):
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]



### 5. 인덱스와 슬라이싱

In [ ]:
# 인덱스는 목차, 순서, 색인 등 몇 번째인지 순서를 의미한다.
# 배열에 있는 데이터는 인덱스를 통해서 접근이 가능하다.
# 일반적으로 0 이상의 인덱스는 앞에서부터의 접근이고, 0 이하의 인덱스는 뒤에서부터의 접근이다.
array_index = np.arange(10)
print_obj(array_index, "np.arange(10)")
print_obj(array_index[0], "array_index[0]")
print_obj(array_index[1], "array_index[1]")
print_obj(array_index[-1], "array_index[-1]")
print_obj(array_index[-3], "array_index[-3]")

# 콜론(:)을 통해서 범위 형태의 인덱스를 지정할 수 있다.
# 일반적으로 콜론 앞뒤의 인덱스 범위 내의 데이터 전체에 접근한다.
print_obj(array_index[0:10], "array_index[0:10]")
print_obj(array_index[0:], "array_index[0:]")
print_obj(array_index[:],"array_index[:]")
print_obj(array_index[:10], "array_index[:10]")
print_obj(array_index[7:], "array_index[7:]")
print_obj(array_index[:5], "array_index[:5]")
print_obj(array_index[2:5], "array_index[2:5]")

# 하나의 인덱스에 두 개의 콜론(:)이 사용된다면, 마지막 콜론 뒤의 숫자는 스텝을 의미한다.
# 스텝은 인덱싱 범위 내에서 얼마만큼 건너뛰며 데이터에 접근할 것인지를 의미한다.
print_obj(array_index[0:10:2], "array_index[0:10:2]")
print_obj(array_index[0:10:3], "array_index[0:10:3]")
print_obj(array_index[2:6:3], "array_index[2:6:3]")
print_obj(array_index[::-1], "array_index[::-1]")
print_obj(array_index[8:5:-1], "array_index[8:5:-1]")
print_obj(array_index[8:5], "array_index[8:5]")

np.arange(10):
[0 1 2 3 4 5 6 7 8 9]

array_index[0]:
0

array_index[1]:
1

array_index[-1]:
9

array_index[-3]:
7

array_index[0:10]:
[0 1 2 3 4 5 6 7 8 9]

array_index[0:]:
[0 1 2 3 4 5 6 7 8 9]

array_index[:]:
[0 1 2 3 4 5 6 7 8 9]

array_index[:10]:
[0 1 2 3 4 5 6 7 8 9]

array_index[7:]:
[7 8 9]

array_index[:5]:
[0 1 2 3 4]

array_index[2:5]:
[2 3 4]

array_index[0:10:2]:
[0 2 4 6 8]

array_index[0:10:3]:
[0 3 6 9]

array_index[2:6:3]:
[2 5]

array_index[::-1]:
[9 8 7 6 5 4 3 2 1 0]

array_index[8:5:-1]:
[8 7 6]

array_index[8:5]:
[]



In [ ]:
array_index = np.arange(9).reshape((3,3))
print_obj(array_index, "array_index")
print_obj(array_index[0][0], "array_index[0][0]")
print_obj(array_index[0,0], "array_index[0,0]")
print_obj(array_index[1,1], "array_index[1,1]")

array_index = np.arange(4*3*2).reshape((4, 3, 2))
print_obj(array_index, "array_index")
print_obj(array_index[2, 1, 0], "array_index[2, 1, 0]")

array_index:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

array_index[0][0]:
0

array_index[0,0]:
0

array_index[1,1]:
4

array_index:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

array_index[2, 1, 0]:
14



In [ ]:
array_index = np.arange(24).reshape((6, 4))
print_obj(array_index, "array_index")
print_obj(array_index[:,[0, 2, 3]], "array_index[idx]")
print_obj(array_index[[0, 2, 3], :], "array_index[idx]")

array_index:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

array_index[idx]:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

array_index[idx]:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]



### 6. 수학적 연산 (Math Operations)

In [ ]:
mat1 = np.arange(6).reshape((3, 2))
mat2 = np.ones((3, 2))
print_obj(mat1, "mat1")
print_obj(mat2, "mat2")
print_obj(mat1 + mat2, "mat1 + mat2")
print_obj(mat1 - mat2, "mat1 - mat2")
print_obj(mat1 * mat2, "mat1 * mat2")
print_obj(mat1 / mat2, "mat1 / mat2")

mat1:
[[0 1]
 [2 3]
 [4 5]]

mat2:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

mat1 + mat2:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

mat1 - mat2:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

mat1 * mat2:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

mat1 / mat2:
[[0. 1.]
 [2. 3.]
 [4. 5.]]



In [ ]:
mat = np.arange(6).reshape((3, 2))
print_obj(mat, "mat")
print_obj(mat.sum(), "mat.sum()")
print_obj(mat.sum(axis = 0), "mat.sum(axis = 0)") # axis는 축을 의미
print_obj(mat.sum(axis = 1), "mat.sum(axis = 1)")
print_obj(mat.mean(), "mat.mean()")
print_obj(mat.max(), "mat.max()")
print_obj(mat.min(), "mat.min()")

mat:
[[0 1]
 [2 3]
 [4 5]]

mat.sum():
15

mat.sum(axis = 0):
[6 9]

mat.sum(axis = 1):
[1 5 9]

mat.mean():
2.5

mat.max():
5

mat.min():
0



In [ ]:
mat1 = np.arange(3).astype('float')
mat2 = np.ones(3)
print_obj(mat1, "mat1")
print_obj(mat2, "mat2")
print_obj(np.dot(mat1, mat2), "mat1 dot mat2")

mat1:
[0. 1. 2.]

mat2:
[1. 1. 1.]

mat1 dot mat2:
3.0



In [ ]:
mat1 = np.arange(6).reshape((3, 2))
mat2 = np.ones((2, 3))
print_obj(mat1, "mat1")
print_obj(mat2, "mat2")
print_obj(np.dot(mat1, mat2), "mat1 dot mat2")
print_obj(mat1 @ mat2, "mat1 @ mat2")
print_obj(np.matmul(mat1, mat2), "matmul(mat1, mat2)")

mat3 = np.arange(24).reshape((4, 3, 2))
mat4 = np.ones((4, 2, 3))
print_obj(mat3, "mat3")
print_obj(mat4, "mat4")
print_obj(np.dot(mat3, mat4).shape, "mat3 dot mat4")
print_obj((mat3 @ mat4).shape, "mat3 @ mat4")
print_obj(np.matmul(mat3, mat4).shape, "matmul(mat3, mat4)")

mat1:
[[0 1]
 [2 3]
 [4 5]]

mat2:
[[1. 1. 1.]
 [1. 1. 1.]]

mat1 dot mat2:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

mat1 @ mat2:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

matmul(mat1, mat2):
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

mat3:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

mat4:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

mat3 dot mat4:
(4, 3, 4, 3)

mat3 @ mat4:
(4, 3, 3)

matmul(mat3, mat4):
(4, 3, 3)



### 7. 형태 변형 (Shape Manipulation)

In [ ]:
array1 = np.arange(24).reshape((2, 3, 4))
print_obj(array1, "np.arange(24).reshape((2, 3, 4))")
array2 = array1.reshape((6, 4))
print_obj(array2, "array1.reshape((6, 4))")
array3 = array1.reshape((6, -1))
print_obj(array3, "array1.reshape((6, -1))")
array4 = array1.reshape((-1, 6))
print_obj(array4, "array1.reshape((-1, 6))")

np.arange(24).reshape((2, 3, 4)):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

array1.reshape((6, 4)):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

array1.reshape((6, -1)):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

array1.reshape((-1, 6)):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]



In [ ]:
array = np.arange(3)
print_obj(array, "array")
print_obj(array[:, None], "array[:, None]")

array:
[0 1 2]

array[:, None]:
[[0]
 [1]
 [2]]



In [ ]:
array1 = np.ones((3, 2))
array2 = np.zeros((3, 2))
print_obj(array1, "array1")
print_obj(array2, "array2")

print_obj(np.vstack([array1, array2]), "array1 + 2 vstack")
print_obj(np.hstack([array1, array2]), "array1 + 2 hstack")
print_obj(np.hstack([array1, array2, array1]), "array1 + 2 + 1 hstack")

print_obj(np.concatenate([array1, array2], axis = 0), "array1 + 2 concat axis = 0")
print_obj(np.concatenate([array1, array2], axis = 1), "array1 + 2 concat axis = 1")

array1:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

array2:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

array1 + 2 vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

array1 + 2 hstack:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

array1 + 2 + 1 hstack:
[[1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]]

array1 + 2 concat axis = 0:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

array1 + 2 concat axis = 1:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]



In [ ]:
array = np.arange(6).reshape((3, 2))
print_obj(array, "array")
print_obj(array.T, "array.T")

array1 = np.arange(24).reshape((4, 3, 2))
print_obj(array1, "array1")
array2 = np.transpose(array1, [0, 2, 1])
print_obj(array2, "Swap axis 1 and 2")
print_obj(array2.shape, "Swapped shape")
array3 = np.transpose(array1, [1, 0, 2])
print_obj(array3, "Swap axis 0 and 1")
print_obj(array3.shape, "Swapped shape")

array:
[[0 1]
 [2 3]
 [4 5]]

array.T:
[[0 2 4]
 [1 3 5]]

array1:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

Swap axis 1 and 2:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]

Swapped shape:
(4, 2, 3)

Swap axis 0 and 1:
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]

Swapped shape:
(3, 4, 2)



### 8. 브로드캐스팅(Broadcasting)

In [ ]:
vector = np.arange(3)
scalar = 2.
print_obj(vector, "vector")
print_obj(scalar, "scalar")
print_obj(vector+scalar, "vector + scalar")
print_obj(vector-scalar, "vector - scalar")
print_obj(vector*scalar, "vector * scalar")
print_obj(vector/scalar, "vector / scalar")

vector:
[0 1 2]

scalar:
2.0

vector + scalar:
[2. 3. 4.]

vector - scalar:
[-2. -1.  0.]

vector * scalar:
[0. 2. 4.]

vector / scalar:
[0.  0.5 1. ]



In [ ]:
mat1 = np.arange(6).reshape((3, 2))
mat2 = np.arange(2).reshape(2) + 1
print_obj(mat1, "mat1")
print_obj(mat2, "mat2")
print_obj(mat1 + mat2, "mat1 + mat2")

mat3 = np.arange(12).reshape((2, 3, 2))
mat4 = np.arange(6).reshape((3, 2))
print_obj(mat3, "mat3")
print_obj(mat4, "mat4")
print_obj(mat3 + mat4, "mat3 + mat4")

mat1:
[[0 1]
 [2 3]
 [4 5]]

mat2:
[1 2]

mat1 + mat2:
[[1 3]
 [3 5]
 [5 7]]

mat3:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

mat4:
[[0 1]
 [2 3]
 [4 5]]

mat3 + mat4:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]

